SELECT ACAD_ORG
       , EFFDT
       , EFF_STATUS
       , DESCR
       , DESCRSHORT
       , DESCRFORMAL
       , INSTITUTION
       , CAMPUS

FROM PS_ACAD_ORG_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY ACAD_ORG, EFFDT