SELECT INSTITUTION
       , ACAD_CAREER
       , ACAD_CALENDAR_ID
       , STRM
       , DEGR_CONFER_DT
       , CENSUS_DT
       , LST_CANCEL_DT
       , CANCEL_REASON
       , LST_WD_WO_PEN_DT
       , WD_WO_PEN_REASON
       , LST_WD_W_PEN_DT
       , WD_W_PEN_GRD_BAS
       , WD_W_PEN_GRADE
       , FULLY_ENRL_DT
       , FULLY_GRADED_DT

FROM PS_ACAD_CALTRM_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY STRM, ACAD_CAREER