SELECT INSTITUTION
       , ACAD_CAREER
       , EFFDT
       , EFF_STATUS
       , DESCR
       , DESCRSHORT
       , GRADING_SCHEME
       , GRADING_BASIS
       , GRADE_TRANSFER
       , REPEAT_SCHEME
       , TERM_TYPE
       , HOLIDAY_SCHEDULE
       , FA_PRIMACY_NBR
       , ACAD_PLAN_TYPE
       , ADVISOR_EDIT
       , LST_TRM_HIST_ENRL
       , FA_CAR_TYPE
       , GRADUATE_LVL_IND
       , REPEAT_RULE
       , TRANSCRIPT_LEVEL

FROM PS_ACAD_CAR_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY ACAD_CAREER, EFFDT