SELECT INSTITUTION
       , ACAD_CAREER
       , EFFDT
       , ACAD_STNDNG_ACTN
       , DESCR
       , DESCRSHORT
       , TRANSCRIPT_LEVEL
       , ACAD_STNDNG_STAT
       , DESCRFORMAL
       , DESCRINTERNAL

FROM PS_ACAD_STACTN_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY ACAD_STNDNG_ACTN, EFFDT