SELECT INSTITUTION
       , ADMIT_TYPE
       , EFFDT
       , EFF_STATUS
       , DESCR
       , DESCRSHORT
       , ACAD_CAREER
       , READMIT_PROCESS

FROM PS_ADMIT_TYPE_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY ADMIT_TYPE, EFFDT