SELECT INSTITUTION
       , ACAD_PLAN
       , ACAD_SUB_PLAN
       , EFFDT
       , EFF_STATUS
       , ACAD_SUBPLAN_TYPE
       , DESCR
       , DESCRSHORT
       , SUBPLN_REQTRM_DFLT
       , DIPLOMA_DESCR
       , DIPLOMA_PRINT_FL
       , DIPLOMA_INDENT
       , TRNSCR_DESCR
       , FIRST_TERM_VALID
       , CIP_CODE
       , HEGIS_CODE
       , TRANSCRIPT_LEVEL
       , EVALUATE_SUBPLAN

FROM PS_ACAD_SUBPLN_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY ACAD_PLAN, ACAD_SUB_PLAN, EFFDT