SELECT CRSE_ID
       , CRSE_OFFER_NBR
       , STRM
       , SESSION_CODE
       , CLASS_SECTION
       , CLASS_MTG_NBR
       , INSTR_ASSIGN_SEQ
       , EMPLID
       , INSTR_ROLE
       , GRADE_RSTR_ACCESS
       , CONTACT_MINUTES
       , SCHED_PRINT_INSTR
       , INSTR_LOAD_FACTOR
       , EMPL_RCD
       , ASSIGN_TYPE
       , WEEK_WORKLOAD_HRS
       , ASSIGNMENT_PCT
       , AUTO_CALC_WRKLD

FROM PS_CLASS_INSTR

ORDER BY CRSE_ID, STRM, CLASS_SECTION