SELECT DEGREE
       , EFFDT
       , EFF_STATUS
       , DESCR
       , DESCRSHORT
       , YEARS_OF_EDUCATN
       , EDUCATION_LVL
       , DESCRFORMAL
       , INTERNAL_DEGREE

FROM PS_DEGREE_TBL

WHERE 1=1

ORDER BY DEGREE, EFFDT