SELECT SETID
       , ETHNIC_GRP_CD
       , EFFDT
       , EFF_STATUS
       , DESCR50
       , DESCRSHORT
       , ETHNIC_CATEGORY
       , ETHNIC_GROUP

FROM PS_ETHNIC_GRP_TBL

WHERE 1=1

ORDER BY ETHNIC_GRP_CD, EFFDT