SELECT EMPLID
       , E_ADDR_TYPE
       , EMAIL_ADDR
       , PREF_EMAIL_FLAG

FROM PS_EMAIL_ADDRESSES

WHERE 1=1
   AND (EMPLID IN (SELECT DISTINCT EMPLID FROM PS_EMPLOYEES
                     WHERE BUSINESS_UNIT = '')
        OR EMPLID IN (SELECT DISTINCT EMPLID FROM PS_STDNT_CAR_TERM
                        WHERE INSTITUTION = ''))

--ORDER BY EMPLID, E_ADDR_TYPE