SELECT SETID
       , GRADING_SCHEME
       , EFFDT
       , GRADING_BASIS
       , CRSE_GRADE_INPUT
       , DESCR
       , DESCRSHORT
       , GRADE_CONVERT
       , GRADE_POINTS
       , EARN_CREDIT
       , INCLUDE_IN_GPA
       , IN_PROGRESS_GRD
       , VALID_ATTEMPT
       , GRADE_CATEGORY
       , EXCLUDE_PRGRSS_UNT
       , SSR_GRADE_FLAG

FROM PS_GRADE_TBL

WHERE 1=1

ORDER BY CRSE_GRADE_INPUT, GRADING_BASIS, EFFDT