SELECT EMPLID
       , PHONE_TYPE
       , COUNTRY_CODE
       , PHONE
       , EXTENSION
       , PREF_PHONE_FLAG

FROM PS_PERSONAL_PHONE

WHERE 1=1
   AND (EMPLID IN (SELECT DISTINCT EMPLID FROM PS_EMPLOYEES
                     WHERE BUSINESS_UNIT = '')
        OR EMPLID IN (SELECT DISTINCT EMPLID FROM PS_STDNT_CAR_TERM
                        WHERE INSTITUTION = ''))

--ORDER BY EMPLID, PHONE_TYPE