SELECT EMPLID
       , BIRTHDATE
       , BIRTHPLACE
       , BIRTHCOUNTRY
       , BIRTHSTATE
       , DT_OF_DEATH

FROM PS_PERSON

WHERE 1=1
   AND (EMPLID IN (SELECT DISTINCT EMPLID FROM PS_EMPLOYEES
                     WHERE BUSINESS_UNIT = '')
        OR EMPLID IN (SELECT DISTINCT EMPLID FROM PS_STDNT_CAR_TERM
                        WHERE INSTITUTION = ''))

--ORDER BY EMPLID