SELECT INSTITUTION
       , SRVC_IND_CD
       , EFFDT
       , SRVC_IND_REASON
       , DESCR
       , DESCRSHORT
       , SRVC_IN_REF_TYPE
       , DEPTID
       , POSITION_NBR
       , DESCRLONG

FROM PS_SRVC_IN_RSN_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY SRVC_IND_CD, EFFDT