SELECT INSTITUTION
       , SRVC_IND_CD
       , EFFDT
       , EFF_STATUS
       , DESCR
       , DESCRSHORT
       , POS_SRVC_INDICATOR
       , SCC_HOLD_DISPLAY
       , DFLT_SRVC_IND_RSN
       , SRV_IND_DCSD_FLAG

FROM PS_SRVC_IND_CD_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY SRVC_IND_CD, EFFDT