SELECT INSTITUTION
       , ACAD_CAREER
       , STRM
       , SESSION_CODE
       , SESS_BEGIN_DT
       , SESS_END_DT
       , ENROLL_OPEN_DT
       , FIRST_ENRL_DT
       , LAST_ENRL_DT
       , LAST_WAIT_DT
       , HOLIDAY_SCHEDULE
       , CENSUS_DT
       , SIXTY_PCT_DT

FROM PS_SESSION_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY STRM, ACAD_CAREER
