SELECT INSTITUTION
       , STDNT_GROUP
       , EFFDT
       , EFF_STATUS
       , DESCR
       , DESCRSHORT

FROM PS_STDNT_GROUP_TBL

WHERE 1=1
   AND INSTITUTION = ''
   
ORDER BY STDNT_GROUP, EFFDT