SELECT INSTITUTION
       , ACAD_CAREER
       , STRM
       , DESCR
       , DESCRSHORT
       , TERM_BEGIN_DT
       , TERM_END_DT
       , SESSION_CODE
       , TERM_CATEGORY
       , ACAD_YEAR
       , HOLIDAY_SCHEDULE
       , SIXTY_PCT_DT

FROM PS_TERM_TBL

WHERE 1=1
   AND INSTITUTION = ''

ORDER BY STRM, ACAD_CAREER