SELECT OPRID
       , VERSION
       , OPRDEFNDESC
       , EMPLID
       , EMAILID
       , OPRCLASS
       , ROWSECCLASS
       , ACCTLOCK

FROM PSOPRDEFN

WHERE 1=1
   AND (EMPLID IN (SELECT DISTINCT EMPLID FROM PS_EMPLOYEES
                     WHERE BUSINESS_UNIT = '')
        OR EMPLID IN (SELECT DISTINCT EMPLID FROM PS_STDNT_CAR_TERM
                        WHERE INSTITUTION = ''))

--ORDER BY EMPLID